### ISSUE TITLE
node.getContext() is not a function

### ISSUE THREAD

**Issue by cpfeiffer** [spring-io/antora-xref-extension#4]
Having a ~~tiny little typo~~ [description list](https://docs.asciidoctor.org/asciidoc/latest/lists/description/) in an asciidoc page causes the following exception, leaving no clue where to look for the cause.
See this example:

```
gRPC port:: 11004
```

leading to this exception:

```
[INFO] [09:16:30.086] FATAL (antora): node.getContext is not a function
[INFO]     Cause: TypeError
[INFO]         at processNode (myproject/node_modules/@springio/antora-xref-extension/lib/index.js:95:26)
[INFO]         at myproject/node_modules/@springio/antora-xref-extension/lib/index.js:109:41
[INFO]         at Array.forEach (<anonymous>)
[INFO]         at processNode (myproject/node_modules/@springio/antora-xref-extension/lib/index.js:109:22)
[INFO]         at myproject/node_modules/@springio/antora-xref-extension/lib/index.js:109:41
[INFO]         at Array.forEach (<anonymous>)
[INFO]         at processNode (myproject/node_modules/@springio/antora-xref-extension/lib/index.js:109:22)
[INFO]         at myproject/node_modules/@springio/antora-xref-extension/lib/index.js:109:41
[INFO]         at Array.forEach (<anonymous>)
[INFO]         at processNode (myproject/node_modules/@springio/antora-xref-extension/lib/index.js:109:22)
```

**Comment by cpfeiffer** [comment]
I just learned that these double colons are actually a thing:
https://docs.asciidoctor.org/asciidoc/latest/lists/description/

**Comment by philwebb** [comment]
Closing in favor of PR #5
